version: '3.9'

services:
  imagemagick:
    build: .
    container_name: imagemagick_test
    volumes:
      - ./container_data:/ # Persist everything, including logs and reports
    stdin_open: true
    tty: true
    command: ["/bin/bash", "-c", "./startup.sh"]
