version: '3.9'

services:
  imagemagick:
    build: .
    container_name: imagemagick_test
    volumes:
      - ./container_opt:/opt  # Persist logs, reports, or generated output
    stdin_open: true
    tty: true
    working_dir: /app        # So ./startup.sh is found
    command: ["/bin/bash", "-c", "./app/startup.sh && ./app//test_imagemagick.sh"]
    environment:
      JFROG_USER: ${JFROG_USER}
      JFROG_APIKEY: ${JFROG_APIKEY}
